# Values for MGOB Helm chart. Production environment.
# https://github.com/stefanprodan/mgob

nameOverride: mgob

backup:
  mongo:
    host: "mongodb-mongodb-replicaset-0.mongodb-mongodb-replicaset.example,mongodb-mongodb-replicaset-1.mongodb-mongodb-replicaset.example,mongodb-mongodb-replicaset-2.mongodb-mongodb-replicaset.example"
    port: 27017
    database: "example"
    username: "root"
    params: "--authenticationDatabase admin"
    secret:
      name: "mongodb-mongodb-replicaset-admin" # Secret for mongodb root password
      key: "password"

  scheduler:
    cron: "00 00 * * *"
    retention: 1
    timeout: 60

  gcloud:
    bucket: "example-backup"
    keysecret: "backup-bucket-credentials"

  slack:
    enabled: true
    url: "https://hooks.slack.com/services/..."
    channel: devops
    username: notification
    warnOnly: false

storage:
  longTerm:
    storageClass: ""
    size: 4Gi
  tmp:
    storageClass: ""
    size: 4Gi

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
