apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "mgob.name" . }}
    chart: {{ template "mgob.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "mgob.fullname" . }}
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    name: {{ .Values.service.name }}
  selector:
    app: {{ template "mgob.fullname" . }}
    release: {{ .Release.Name }}
